title: Krithika

email:  krithika@iitm.ac.in

description: >
  This lab's goal ... 

timezone: "Asia/Kolkata"
  
baseurl: "" 
url    : "https://krithikasivaram.github.io"

include: ['_pages']

collections:
  news:
  events:
  project:
  research:
  members:
     permalink: /:collection/:path/
     output: true

future: true

authors:
  krithika:
    name: Krithika Narayanaswamy
